export type DropshipPartner = {
  name: string;
  rating: number;
  reviews: string;
  usFulfillment: string;
  avgShipDays: string;
  specialty: string;
  url: string;
};

export type TeeColor =
  | "white"
  | "yellow"
  | "navy"
  | "red"
  | "orange"
  | "skyblue"
  | "green";

export type TeeProduct = {
  id: string;
  name: string;
  price: number;
  phrase: string;
  teeColor: TeeColor;
  city: string;
  state: string;
  theme: string;
  tagline: string;
  partner: string;
  category: "city" | "country";
  countryCode?: string;
  backLabel: string;
  backSlogan: string;
  flagCode: string;
  image?: string;
  badge?: string;
  accent: string;
};

export const DROPSHIP_PARTNERS: DropshipPartner[] = [
  {
    name: "Printful",
    rating: 4.7,
    reviews: "12,000+",
    usFulfillment: "Charlotte NC · Dallas TX · San Jose CA",
    avgShipDays: "2–5 business days",
    specialty: "Premium tees, sleeve embroidery, posters",
    url: "https://www.printful.com",
  },
  {
    name: "Printify",
    rating: 4.6,
    reviews: "8,500+",
    usFulfillment: "90+ US print providers",
    avgShipDays: "2–7 business days",
    specialty: "City & nation tees, hoodies, hats",
    url: "https://www.printify.com",
  },
  {
    name: "Spocket",
    rating: 4.5,
    reviews: "4,200+",
    usFulfillment: "US suppliers, 2–7 day ship",
    avgShipDays: "2–7 business days",
    specialty: "Curated US brands, fan apparel",
    url: "https://www.spocket.co",
  },
  {
    name: "Gooten",
    rating: 4.6,
    reviews: "3,100+",
    usFulfillment: "US production facilities",
    avgShipDays: "3–6 business days",
    specialty: "Wall art, blankets, accessories",
    url: "https://www.gooten.com",
  },
];

/** Every tee: catchy phrase + FIFA trophy on right sleeve top */
export const TEE_PRODUCTS: TeeProduct[] = [
  // —— US HOST CITIES (mostly white) ——
  {
    id: "nj-empire",
    name: "Empire State Final Tee",
    price: 34.99,
    phrase: "EMPIRE STATE OF SOCCER",
    teeColor: "white",
    city: "East Rutherford",
    state: "NJ",
    theme: "Empire State · Garden State",
    tagline: "NYC skyline chest print · trophy on right sleeve",
    partner: "Printful",
    category: "city",
    badge: "FINAL HOST",
    backLabel: "East Rutherford",
    backSlogan: "Where legends are crowned",
    flagCode: "us",
    accent: "#ffd700",
    image: "/images/tees/tee-nj-empire.png",
  },
  {
    id: "nj-garden",
    name: "Garden State Glory Tee",
    price: 32.99,
    phrase: "GARDEN STATE — WE HOST THE WORLD",
    teeColor: "white",
    city: "East Rutherford",
    state: "NJ",
    theme: "The Garden State",
    tagline: "Green & gold accents · MetLife pride",
    partner: "Printify",
    category: "city",
    backLabel: "New Jersey",
    backSlogan: "Garden State hosts the world",
    flagCode: "us",
    accent: "#00a651",
    image: "/images/tees/tee-nj-garden.png",
  },
  {
    id: "la-angel",
    name: "City of Angels Tee",
    price: 34.99,
    phrase: "ANGELS ON THE PITCH",
    teeColor: "white",
    city: "Los Angeles",
    state: "CA",
    theme: "City of Angels",
    tagline: "SoFi Stadium edition · purple & gold",
    partner: "Printful",
    category: "city",
    backLabel: "Los Angeles",
    backSlogan: "City of angels, city of goals",
    flagCode: "us",
    accent: "#7c3aed",
    image: "/images/tees/tee-la.png",
  },
  {
    id: "mia-magic",
    name: "Magic City Kickoff Tee",
    price: 33.99,
    phrase: "MAGIC CITY KICKOFF",
    teeColor: "white",
    city: "Miami",
    state: "FL",
    theme: "Magic City",
    tagline: "Neon pink & teal · Hard Rock host",
    partner: "Printify",
    category: "city",
    badge: "BRONZE MATCH",
    backLabel: "Miami",
    backSlogan: "Magic City, global heat",
    flagCode: "us",
    accent: "#ec4899",
    image: "/images/tees/tee-miami.png",
  },
  {
    id: "dal-lone",
    name: "Lone Star Legends Tee",
    price: 31.99,
    phrase: "LONE STAR LEGENDS",
    teeColor: "white",
    city: "Arlington",
    state: "TX",
    theme: "Lone Star State",
    tagline: "Semifinal venue · star on sleeve",
    partner: "Printful",
    category: "city",
    badge: "SEMIFINAL",
    backLabel: "Dallas",
    backSlogan: "Lone Star legends rise",
    flagCode: "us",
    accent: "#dc2626",
    image: "/images/tees/tee-dallas.png",
  },
  {
    id: "sea-emerald",
    name: "Emerald Dream Tee",
    price: 32.99,
    phrase: "EMERALD DREAM",
    teeColor: "white",
    city: "Seattle",
    state: "WA",
    theme: "Emerald City",
    tagline: "Lumen Field roar · mountain vibes",
    partner: "Spocket",
    category: "city",
    backLabel: "Seattle",
    backSlogan: "Emerald City roars loud",
    flagCode: "us",
    accent: "#10b981",
    image: "/images/tees/tee-seattle.png",
  },
  {
    id: "atl-rise",
    name: "Rise Up For Glory Tee",
    price: 30.99,
    phrase: "RISE UP FOR GLORY",
    teeColor: "white",
    city: "Atlanta",
    state: "GA",
    theme: "Empire State of the South",
    tagline: "Mercedes-Benz knockout energy",
    partner: "Printify",
    category: "city",
    backLabel: "Atlanta",
    backSlogan: "Rise up for glory",
    flagCode: "us",
    accent: "#c8102e",
    image: "/images/tees/tee-atlanta.png",
  },
  {
    id: "phi-brotherly",
    name: "Brotherly Goal Tee",
    price: 29.99,
    phrase: "BROTHERLY GOAL",
    teeColor: "white",
    city: "Philadelphia",
    state: "PA",
    theme: "City of Brotherly Love",
    tagline: "Lincoln Financial passion wear",
    partner: "Printify",
    category: "city",
    backLabel: "Philadelphia",
    backSlogan: "Brotherly love, world game",
    flagCode: "us",
    accent: "#006341",
    image: "/images/tees/tee-philly.png",
  },
  {
    id: "sf-golden",
    name: "Bay Area United Tee",
    price: 33.99,
    phrase: "BAY AREA UNITED",
    teeColor: "white",
    city: "Santa Clara",
    state: "CA",
    theme: "Golden Gate Bay Area",
    tagline: "Levi's Stadium · bridge silhouette",
    partner: "Spocket",
    category: "city",
    backLabel: "Bay Area",
    backSlogan: "United by the golden gate",
    flagCode: "us",
    accent: "#f97316",
    image: "/images/tees/tee-sf.png",
  },
  {
    id: "hou-space",
    name: "Space City FC Tee",
    price: 29.99,
    phrase: "SPACE CITY FC",
    teeColor: "white",
    city: "Houston",
    state: "TX",
    theme: "Space City",
    tagline: "NRG Stadium · rocket accent",
    partner: "Gooten",
    category: "city",
    backLabel: "Houston",
    backSlogan: "Space City shoots for stars",
    flagCode: "us",
    accent: "#2563eb",
    image: "/images/tees/tee-houston.png",
  },
  {
    id: "bos-beantown",
    name: "Beantown Believers Tee",
    price: 31.99,
    phrase: "BEANTOWN BELIEVERS",
    teeColor: "white",
    city: "Foxborough",
    state: "MA",
    theme: "Beantown",
    tagline: "Gillette · New England soccer pride",
    partner: "Printful",
    category: "city",
    backLabel: "Boston",
    backSlogan: "Beantown believers unite",
    flagCode: "us",
    accent: "#1d4ed8",
    image: "/images/tees/tee-boston.png",
  },
  {
    id: "kc-heart",
    name: "Heart of the Game Tee",
    price: 28.99,
    phrase: "HEART OF THE GAME",
    teeColor: "white",
    city: "Kansas City",
    state: "MO",
    theme: "Heart of America",
    tagline: "Arrowhead roar meets the world game",
    partner: "Printify",
    category: "city",
    backLabel: "Kansas City",
    backSlogan: "Heart of America beats",
    flagCode: "us",
    accent: "#e11d48",
    image: "/images/tees/tee-kc.png",
  },
  // —— NATION TEES (authentic team colors) ——
  {
    id: "col-cafeteros",
    name: "Los Cafeteros Rise Tee",
    price: 34.99,
    phrase: "LOS CAFETEROS RISE",
    teeColor: "yellow",
    city: "US Host Cities",
    state: "INTL",
    theme: "Colombia",
    tagline: "Amarillo es el color · Group K pride",
    partner: "Printful",
    category: "country",
    countryCode: "co",
    backLabel: "Colombia",
    backSlogan: "Amarillo es el color",
    flagCode: "co",
    accent: "#fcd116",
    image: "/images/tees/tee-colombia.png",
  },
  {
    id: "ecu-tri",
    name: "La Tri — Sí Se Puede Tee",
    price: 33.99,
    phrase: "LA TRI — SI SE PUEDE",
    teeColor: "yellow",
    city: "US Host Cities",
    state: "INTL",
    theme: "Ecuador",
    tagline: "Yellow kit energy · Group E",
    partner: "Printify",
    category: "country",
    countryCode: "ec",
    backLabel: "Ecuador",
    backSlogan: "La Tri — sí se puede",
    flagCode: "ec",
    accent: "#ffdd00",
    image: "/images/tees/tee-ecuador.png",
  },
  {
    id: "bra-samba",
    name: "Samba Kings Tee",
    price: 35.99,
    phrase: "SAMBA KINGS — JOGO BONITO",
    teeColor: "yellow",
    city: "US Host Cities",
    state: "INTL",
    theme: "Brazil",
    tagline: "Canarinho yellow · Group C favorites",
    partner: "Printful",
    category: "country",
    countryCode: "br",
    backLabel: "Brazil",
    backSlogan: "Samba kings — jogo bonito",
    flagCode: "br",
    accent: "#009c3b",
    image: "/images/tees/tee-brazil.png",
  },
  {
    id: "mex-vamos",
    name: "¡Vamos México! Tee",
    price: 33.99,
    phrase: "¡VAMOS MÉXICO!",
    teeColor: "white",
    city: "Mexico City",
    state: "INTL",
    theme: "Mexico",
    tagline: "Opening match hosts · green & red",
    partner: "Printify",
    category: "country",
    countryCode: "mx",
    badge: "OPENING MATCH",
    backLabel: "México",
    backSlogan: "¡Vamos México!",
    flagCode: "mx",
    accent: "#006847",
    image: "/images/tees/tee-mexico.png",
  },
  {
    id: "usa-stars",
    name: "Stars & Stripes Forever Tee",
    price: 32.99,
    phrase: "STARS & STRIPES FOREVER",
    teeColor: "white",
    city: "US Host Cities",
    state: "INTL",
    theme: "USA",
    tagline: "Home nation pride · Group D",
    partner: "Printful",
    category: "country",
    countryCode: "us",
    backLabel: "USA",
    backSlogan: "Stars & stripes forever",
    flagCode: "us",
    accent: "#3c5bff",
    image: "/images/tees/tee-usa.png",
  },
  {
    id: "ger-eagle",
    name: "Die Mannschaft Tee",
    price: 34.99,
    phrase: "DIE MANNSCHAFT — ALLEZ",
    teeColor: "white",
    city: "US Host Cities",
    state: "INTL",
    theme: "Germany",
    tagline: "Black & gold trim · Group E",
    partner: "Spocket",
    category: "country",
    countryCode: "de",
    backLabel: "Germany",
    backSlogan: "Die Mannschaft — allez",
    flagCode: "de",
    accent: "#000000",
    image: "/images/tees/tee-germany.png",
  },
  {
    id: "arg-albiceleste",
    name: "Albiceleste Pride Tee",
    price: 34.99,
    phrase: "VAMOS ALBICELESTE",
    teeColor: "skyblue",
    city: "US Host Cities",
    state: "INTL",
    theme: "Argentina",
    tagline: "Celeste & white · Group J favorites",
    partner: "Printful",
    category: "country",
    countryCode: "ar",
    backLabel: "Argentina",
    backSlogan: "Vamos Albiceleste",
    flagCode: "ar",
    accent: "#74acdf",
    image: "/images/tees/tee-argentina.png",
  },
  {
    id: "fra-bleus",
    name: "Allez Les Bleus Tee",
    price: 34.99,
    phrase: "ALLEZ LES BLEUS",
    teeColor: "navy",
    city: "US Host Cities",
    state: "INTL",
    theme: "France",
    tagline: "Bleu kit energy · defending champs",
    partner: "Printify",
    category: "country",
    countryCode: "fr",
    backLabel: "France",
    backSlogan: "Allez les Bleus",
    flagCode: "fr",
    accent: "#002395",
    image: "/images/tees/tee-france.png",
  },
  {
    id: "esp-roja",
    name: "La Roja Mundial Tee",
    price: 33.99,
    phrase: "¡A POR EL MUNDIAL!",
    teeColor: "red",
    city: "US Host Cities",
    state: "INTL",
    theme: "Spain",
    tagline: "Roja passion · European flair",
    partner: "Spocket",
    category: "country",
    countryCode: "es",
    backLabel: "España",
    backSlogan: "¡A por el mundial!",
    flagCode: "es",
    accent: "#c60b1e",
    image: "/images/tees/tee-spain.png",
  },
  {
    id: "ned-oranje",
    name: "Oranje Boven Tee",
    price: 33.99,
    phrase: "ORANJE BOVEN ALLES",
    teeColor: "orange",
    city: "US Host Cities",
    state: "INTL",
    theme: "Netherlands",
    tagline: "Total Football orange · Group F",
    partner: "Printify",
    category: "country",
    countryCode: "nl",
    backLabel: "Netherlands",
    backSlogan: "Oranje boven alles",
    flagCode: "nl",
    accent: "#ff6600",
    image: "/images/tees/tee-netherlands.png",
  },
  {
    id: "uru-celeste",
    name: "La Garra Celeste Tee",
    price: 32.99,
    phrase: "CELESTE — LA GARRA",
    teeColor: "skyblue",
    city: "US Host Cities",
    state: "INTL",
    theme: "Uruguay",
    tagline: "Sky blue warriors · Group H grit",
    partner: "Gooten",
    category: "country",
    countryCode: "uy",
    backLabel: "Uruguay",
    backSlogan: "Celeste — la garra",
    flagCode: "uy",
    accent: "#55acee",
    image: "/images/tees/tee-uruguay.png",
  },
  {
    id: "por-forca",
    name: "Força Portugal Tee",
    price: 33.99,
    phrase: "FORÇA PORTUGAL",
    teeColor: "red",
    city: "US Host Cities",
    state: "INTL",
    theme: "Portugal",
    tagline: "Seleção das Quinas · red kit pride",
    partner: "Printful",
    category: "country",
    countryCode: "pt",
    backLabel: "Portugal",
    backSlogan: "Força Portugal",
    flagCode: "pt",
    accent: "#006600",
    image: "/images/tees/tee-portugal.png",
  },
  {
    id: "eng-home",
    name: "It's Coming Home Tee",
    price: 32.99,
    phrase: "IT'S COMING HOME",
    teeColor: "white",
    city: "US Host Cities",
    state: "INTL",
    theme: "England",
    tagline: "Three Lions roar · white home kit",
    partner: "Printify",
    category: "country",
    countryCode: "gb-eng",
    backLabel: "England",
    backSlogan: "It's coming home",
    flagCode: "gb-eng",
    accent: "#c8102e",
    image: "/images/tees/tee-england.png",
  },
  {
    id: "jpn-samurai",
    name: "Samurai Blue Rise Tee",
    price: 33.99,
    phrase: "SAMURAI BLUE RISE",
    teeColor: "white",
    city: "US Host Cities",
    state: "INTL",
    theme: "Japan",
    tagline: "Samurai Blue spirit · Group C",
    partner: "Spocket",
    category: "country",
    countryCode: "jp",
    backLabel: "Japan",
    backSlogan: "Samurai Blue rise",
    flagCode: "jp",
    accent: "#0b1f4d",
    image: "/images/tees/tee-japan.png",
  },
  {
    id: "mar-atlas",
    name: "Atlas Lions Tee",
    price: 33.99,
    phrase: "أسود الأطلس — VAMOS",
    teeColor: "red",
    city: "US Host Cities",
    state: "INTL",
    theme: "Morocco",
    tagline: "Atlas Lions red · African pride",
    partner: "Printify",
    category: "country",
    countryCode: "ma",
    backLabel: "Morocco",
    backSlogan: "Atlas Lions — vamos",
    flagCode: "ma",
    accent: "#006233",
    image: "/images/tees/tee-morocco.png",
  },
];
