import type { Match } from "@/lib/scores/types";

/** International friendlies — pre-tournament, all nil-nil */
export const FRIENDLY_MATCHES: Match[] = [
  {
    id: "f1",
    competition: "friendly",
    status: "scheduled",
    date: "Mar 22",
    time: "8:00 PM ET",
    home: { name: "USA", code: "us" },
    away: { name: "Mexico", code: "mx" },
    venue: "AT&T Stadium",
    city: "Arlington, TX",
    stage: "International Friendly",
    score: { home: 0, away: 0 },
  },
  {
    id: "f2",
    competition: "friendly",
    status: "scheduled",
    date: "Mar 25",
    time: "3:00 PM ET",
    home: { name: "Brazil", code: "br" },
    away: { name: "Argentina", code: "ar" },
    venue: "MetLife Stadium",
    city: "East Rutherford, NJ",
    stage: "International Friendly",
    score: { home: 0, away: 0 },
  },
  {
    id: "f3",
    competition: "friendly",
    status: "scheduled",
    date: "Mar 26",
    time: "2:45 PM ET",
    home: { name: "England", code: "gb-eng" },
    away: { name: "Belgium", code: "be" },
    venue: "Wembley Stadium",
    city: "London",
    stage: "International Friendly",
    score: { home: 0, away: 0 },
  },
  {
    id: "f4",
    competition: "friendly",
    status: "scheduled",
    date: "Mar 28",
    time: "7:00 PM ET",
    home: { name: "France", code: "fr" },
    away: { name: "Germany", code: "de" },
    venue: "Stade de France",
    city: "Paris",
    stage: "International Friendly",
    score: { home: 0, away: 0 },
  },
  {
    id: "f5",
    competition: "friendly",
    status: "scheduled",
    date: "Mar 29",
    time: "4:00 PM ET",
    home: { name: "Colombia", code: "co" },
    away: { name: "Spain", code: "es" },
    venue: "Hard Rock Stadium",
    city: "Miami Gardens, FL",
    stage: "International Friendly",
    score: { home: 0, away: 0 },
  },
  {
    id: "f6",
    competition: "friendly",
    status: "scheduled",
    date: "Apr 2",
    time: "9:00 PM ET",
    home: { name: "Canada", code: "ca" },
    away: { name: "Netherlands", code: "nl" },
    venue: "BC Place",
    city: "Vancouver",
    stage: "International Friendly",
    score: { home: 0, away: 0 },
  },
];
