export type Stadium = {
  id: string;
  name: string;
  city: string;
  state: string;
  nickname: string;
  capacity: number;
  matches: number;
  highlight: string;
  opened: string;
  surface: string;
  hostNation: "USA" | "Canada" | "Mexico";
  lat: number;
  lng: number;
};

export const US_STADIUMS: Stadium[] = [
  {
    id: "metlife",
    name: "MetLife Stadium",
    city: "East Rutherford",
    state: "NJ",
    nickname: "Empire State · Garden State Final",
    capacity: 82500,
    matches: 8,
    highlight: "World Cup Final — July 19, 2026",
    opened: "2010",
    surface: "UBU Speed Series S5-M",
    hostNation: "USA",
    lat: 40.8135,
    lng: -74.0745,
  },
  {
    id: "sofi",
    name: "SoFi Stadium",
    city: "Inglewood",
    state: "CA",
    nickname: "City of Angels",
    capacity: 70000,
    matches: 7,
    highlight: "USA quarterfinal venue",
    opened: "2020",
    surface: "Matrix Turf",
    hostNation: "USA",
    lat: 33.9535,
    lng: -118.3392,
  },
  {
    id: "att",
    name: "AT&T Stadium",
    city: "Arlington",
    state: "TX",
    nickname: "Lone Star State",
    capacity: 80000,
    matches: 7,
    highlight: "Semifinal host",
    opened: "2009",
    surface: "Hellas Matrix Turf",
    hostNation: "USA",
    lat: 32.7473,
    lng: -97.0945,
  },
  {
    id: "mercedes",
    name: "Mercedes-Benz Stadium",
    city: "Atlanta",
    state: "GA",
    nickname: "Empire State of the South",
    capacity: 71000,
    matches: 6,
    highlight: "Group stage & knockout hub",
    opened: "2017",
    surface: "FieldTurf CORE",
    hostNation: "USA",
    lat: 33.7553,
    lng: -84.4006,
  },
  {
    id: "hardrock",
    name: "Hard Rock Stadium",
    city: "Miami Gardens",
    state: "FL",
    nickname: "Magic City",
    capacity: 64767,
    matches: 6,
    highlight: "Third-place playoff venue",
    opened: "1987",
    surface: "Natural grass",
    hostNation: "USA",
    lat: 25.958,
    lng: -80.2389,
  },
  {
    id: "levis",
    name: "Levi's Stadium",
    city: "Santa Clara",
    state: "CA",
    nickname: "Golden Gate Bay Area",
    capacity: 68500,
    matches: 6,
    highlight: "Silicon Valley showcase",
    opened: "2014",
    surface: "Tifway 419 Bermuda",
    hostNation: "USA",
    lat: 37.403,
    lng: -121.9697,
  },
  {
    id: "lumen",
    name: "Lumen Field",
    city: "Seattle",
    state: "WA",
    nickname: "Emerald City",
    capacity: 69000,
    matches: 5,
    highlight: "Pacific Northwest atmosphere",
    opened: "2002",
    surface: "FieldTurf Revolution 360",
    hostNation: "USA",
    lat: 47.5952,
    lng: -122.3316,
  },
  {
    id: "lincoln",
    name: "Lincoln Financial Field",
    city: "Philadelphia",
    state: "PA",
    nickname: "City of Brotherly Love",
    capacity: 69796,
    matches: 5,
    highlight: "Passionate East Coast crowds",
    opened: "2003",
    surface: "Desso GrassMaster",
    hostNation: "USA",
    lat: 39.9008,
    lng: -75.1675,
  },
  {
    id: "nrg",
    name: "NRG Stadium",
    city: "Houston",
    state: "TX",
    nickname: "Space City",
    capacity: 72220,
    matches: 5,
    highlight: "Diverse global fanbase",
    opened: "2002",
    surface: "Hellas Matrix Turf",
    hostNation: "USA",
    lat: 29.6847,
    lng: -95.4107,
  },
  {
    id: "gillette",
    name: "Gillette Stadium",
    city: "Foxborough",
    state: "MA",
    nickname: "Beantown",
    capacity: 65878,
    matches: 5,
    highlight: "New England soccer energy",
    opened: "2002",
    surface: "FieldTurf CORE",
    hostNation: "USA",
    lat: 42.0909,
    lng: -71.2643,
  },
  {
    id: "arrowhead",
    name: "GEHA Field at Arrowhead Stadium",
    city: "Kansas City",
    state: "MO",
    nickname: "Heart of America",
    capacity: 76416,
    matches: 4,
    highlight: "Loudest fans on earth",
    opened: "1972",
    surface: "Grass",
    hostNation: "USA",
    lat: 39.0489,
    lng: -94.4839,
  },
];

export const ALL_STADIUMS: Stadium[] = [
  ...US_STADIUMS,
  {
    id: "azteca",
    name: "Estadio Azteca",
    city: "Mexico City",
    state: "CDMX",
    nickname: "El Coloso",
    capacity: 87523,
    matches: 5,
    highlight: "Opening match — June 11",
    opened: "1966",
    surface: "Natural grass",
    hostNation: "Mexico",
    lat: 19.3029,
    lng: -99.1505,
  },
  {
    id: "bmo",
    name: "BMO Field",
    city: "Toronto",
    state: "ON",
    nickname: "The Six",
    capacity: 45000,
    matches: 6,
    highlight: "Canada's home ground",
    opened: "2007",
    surface: "Natural grass",
    hostNation: "Canada",
    lat: 43.6332,
    lng: -79.4186,
  },
  {
    id: "bcplace",
    name: "BC Place",
    city: "Vancouver",
    state: "BC",
    nickname: "Pacific Gateway",
    capacity: 54500,
    matches: 5,
    highlight: "Mountain-to-sea backdrop",
    opened: "1983",
    surface: "Polytan LigaGrass",
    hostNation: "Canada",
    lat: 49.2768,
    lng: -123.112,
  },
  {
    id: "akron",
    name: "Estadio Akron",
    city: "Guadalajara",
    state: "Jalisco",
    nickname: "Pearl of the West",
    capacity: 49850,
    matches: 4,
    highlight: "Chivas heartland",
    opened: "2010",
    surface: "Natural grass",
    hostNation: "Mexico",
    lat: 20.6818,
    lng: -103.4626,
  },
  {
    id: "bbva",
    name: "Estadio BBVA",
    city: "Monterrey",
    state: "Nuevo León",
    nickname: "Sultana of the North",
    capacity: 53500,
    matches: 4,
    highlight: "Northern Mexico fortress",
    opened: "2015",
    surface: "Natural grass",
    hostNation: "Mexico",
    lat: 25.6866,
    lng: -100.2451,
  },
];
